// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udqmnxpjbzgqyhpsrnns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkcW1ueHBqYnpncXlocHNybm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTk0MjUsImV4cCI6MjA3MDA3NTQyNX0.MR7Ux1R2et6041Ib7ksnT9dQP1EbgqDpvU9ANj5ECSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});